### ISSUE TITLE
Remove Twig caching in dev

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#1350]
```yaml
twig.cache_extension.strategy.black_hole:
    class: Twig\CacheExtension\CacheStrategy\BlackholeCacheStrategy

  twig.cache_extension:
    class: Twig\CacheExtension\Extension
    arguments:
      $cacheStrategy: '@twig.cache_extension.strategy.black_hole'
    tags:
      - { name: twig.extension }
```
