### ISSUE TITLE
ConfigLoader loads unquoted numbers as objects

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#148]
When using `ConfigLoader` to load Symfony configuration in JavaScript, unquoted integers get parsed as objects. 

For example, when there is the following in `parameters.yml`:

```yml
app.dispatch_port: 8009
app.tracking_port: 8010
app.order_tracking_port: 8011
app.restaurant_panel_port: 8013
```

The resulting configuration is like this:

```json
parameters: {
  "app.dispatch_port": {},
  "app.tracking_port": {},
  "app.order_tracking_port": {},
  "app.restaurant_panel_port": {},
}
```

Right now, it works because we have quoted numbers in `parameters.yml.dist`

See also #20
