### ISSUE TITLE
Index images of shops/products in Typesense 

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#3548]
Linked to coopcycle/coopcycle-app#1469

To have nice search results, we want to index images of shops/products in Typesense. 

The [TypesenseBundle](https://github.com/acseo/TypesenseBundle) invokes [DoctrineToTypesenseTransformer::convert](https://github.com/acseo/TypesenseBundle/blob/9cc51e6274f60237a40e28c0df7d56d4aa8dbe87/src/Transformer/DoctrineToTypesenseTransformer.php) to obtain the data that will land in the index, as defined in the bundle configuration:

https://github.com/coopcycle/coopcycle-web/blob/ecd5e00aa4a5cc5750f91aa15dc98845ad303401/app/config/config.yml#L1003-L1031

For now, it's only possible to use getters on the entity. The problem is that we need some services to obtain the URL of an image. For example, for shops, we need to do this:
https://github.com/coopcycle/coopcycle-web/blob/ecd5e00aa4a5cc5750f91aa15dc98845ad303401/src/Serializer/RestaurantNormalizer.php#L69-L78

---

We would need to be able to call a method from a service, instead of getters. 

For example, the configuration would look like this: 

```
fields:
    image_url:
        entity_attribute: 'AppBundle\Typesense\Converter\ShopConverter::getImageURL'
        name: image_url
        type: string
```

And then the class would accept the entity as parameter: 

```
class ShopConverter 
{
    public function getImageURL($shop): string
    {
        // Use injected service to generate image URL
    }
}
```
